### PR TITLE
Improvements: little fixes and new 'custom_segmentation' field

### LINKED ISSUE #382: --plain does not provide processable output when new version is available
**Describe the bug**
When a new version is available, a banner gets appended to the output of commands, including one run with the `--plain` flag.

[According to the wiki and help](https://github.com/crowdin/crowdin-cli/wiki/List-project-target-languages), the `--plain` flag is supposed to "Provide plain, processable output" - the banner however is not very much processable.

**To Reproduce**
1. Use an outdated version of crowdin cli.
2. Execute CLI command: `crowdin list languages --plain`
3. Notice the version banner at the bottom

**Expected behavior**
Don't output the version banner when the `--plain` flag is provided

**Environment:**
irrelevant
 
**Screenshots**
image

**Additional context**
As a workaround, one can modify the output before processing it, for example by piping it through sed replacing everything past the two newlines: `sed -z 's/\n\n.*/\n/g'`, however, the ideal situation imho would be respecting the `--plain`.

### LINKED ISSUE #383: 'streamIsEmpty' error should fail the program execution
**Description**
`crowdin push sources` exits with 0 despite the `streamIsEmpty` error shown in log.
> :x: Wrong parameters:
  <key: fileStream, code: streamIsEmpty, message: Stream size is null. Not empty content expected>

**To Reproduce**
Execute `crowdin push sources` with some of the source files being empty.

**Expected behavior**
`crowdin push sources` should exit with 1 to clearly indicate an error.

**Environment:**
Ubuntu 18.04.5 LTS

### PR DESCRIPTION
**Pull request by frombetelgeuse**

### CODE REVIEW

File: src/main/java/com/crowdin/cli/client/CrowdinProjectClient.java [hunk 1]
```diff
@@ -164,9 +164,13 @@ public void deleteDirectory(Long directoryId) {
     }
 
     @Override
-    public void updateSource(Long sourceId, UpdateFileRequest request) {
+    public void updateSource(Long sourceId, UpdateFileRequest request) throws ResponseException {
+        Map<BiPredicate<String, String>, ResponseException> errorHandlers = new LinkedHashMap<BiPredicate<String, String>, ResponseException>() {{
+            put((code, message) -> message.contains("File from storage with id #" + request.getStorageId() + " was not found"), new RepeatException());
+            put((code, message) -> StringUtils.contains(message, "Invalid SRX specified"), new ResponseException("Invalid SRX file specified"));
```
Comment (nazar-1) [inline src/main/java/com/crowdin/cli/client/CrowdinProjectClient.java:170]: Add to addSource() method

**Review by andrii-bodnar — APPROVED** [review]

**Review by t10-13rocket — APPROVED** [review]
LGTM

File: src/main/java/com/crowdin/cli/client/CrowdinProjectClient.java (hunk 1 above)
Comment (t10-13rocket) [reply src/main/java/com/crowdin/cli/client/CrowdinProjectClient.java:170]: LGTM
