### PR TITLE
fix: windows escape symbols

### LINKED ISSUE #679: Download sources finds no source files under Windows
**Describe the bug**
Command `download sources` finds no source files to download.

**To Reproduce**
`list sources` works fine
```
crowdin list sources --identity .crowdin.yml --branch="releases-7.3.3"  --verbose
[OK] Fetching project info
[OK] File 'src\main\resources\translations\en\SuggestionTexts.properties'
```
but `pull sources` fails.
```
crowdin pull sources --identity .crowdin.yml --branch="releases-7.3.3"  --verbose
[OK] Fetching project info
[WARNING] No sources found for '\src\main\resources\translations\en\*' pattern. Check the source paths in your configuration file
```
The configuration is:
```yml
preserve_hierarchy: true
files:
  - source: /src/main/resources/translations/en/*
    translation: /src/main/resources/translations/%two_letters_code%/%original_file_name%
    escape_special_characters: 0
    escape_quotes: 0
    export_only_approved: true
```
I tried removing the first `/` from the `source` field in `crowdin.yml` but it didn't help.

**Expected behavior**
`crowdin list sources --identity .crowdin.yml --branch="releases-7.3.3"  --verbose` should output
```
✔️  Fetching project info
✔️  File 'src/main/resources/translations/en/SuggestionTexts.properties'
```

**Environment:**
 - OS: Windows 11 Pro
 - Version 3.15.0

**Additional context**
It works fine with Crowdin CLI 3.15.0 under Ubuntu.

### PR DESCRIPTION
**Pull request by katerina20**

### CODE REVIEW

File: src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java [hunk 1]
```diff
@@ -228,13 +230,13 @@ public List<String> formatForRegex(List<String> toFormat, boolean onProjectLangs
...
-        if(Utils.isWindows()){
+        if (isWindows()) {
             toFormat = toFormat
-                    .replace("\\", "\\\\");
+                .replace("\\", "\\\\");
         }
         toFormat = toFormat
             .replace(ESCAPE_DOT, ESCAPE_DOT_PLACEHOLDER)
-            .replace(DOT, ESCAPE_DOT)
+            .replace(DOT, "\\.")
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java]: Why not use the constant here?

File: src/main/java/com/crowdin/cli/utils/Utils.java [hunk 2]
```diff
@@ -87,7 +87,12 @@ public static String buildUserAgent() {
     }
 
     public static String unixPath(String path) {
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/utils/Utils.java]: This method is only meant to be used on Unix platforms, isn't it? 

We have a separate `windowsPath` method below.

Something is wrong with the `isWindows` condition inside the `unixPath` method.

File: src/test/java/com/crowdin/cli/utils/UtilsTest.java [hunk 3]
```diff
@@ -36,8 +38,15 @@ public void testBuildUserAgent() {
     }
 
     @Test
-    public void testUnixPath() {
-        assertEquals("/path/to/file", Utils.unixPath("\\path\\to\\file"));
+    @DisabledOnOs({OS.LINUX, OS.MAC})
```
Comment (andrii-bodnar) [inline src/test/java/com/crowdin/cli/utils/UtilsTest.java:41]: should we test this method on Windows?

**Review by andrii-bodnar — APPROVED** [review]
