### PR TITLE
fix: suppress progress output for crowdin file download with --no-progress

### LINKED ISSUE #878: crowdin file download command ignores `--no-progress` option
**Describe the bug**
Try to run `crowdin file download` with `--no-progress` option.
The progress still be shown

**To Reproduce**
1. Configuration file: Irrelevant
2. Execute CLI command: 'crowdin file download "/Example.txt' -d ./Example.txt
3. See the progress of fetching project info

**Expected behavior**
No spinner/progress should be shown, when the command is running with `--no-progress` option

**Environment:**
 - OS: macOS
 - Version 14.5

**Screenshots**

**Additional context**

It seems that these parameters are totally ignored and when calling  FileDownloadTranslation action
https://github.com/crowdin/crowdin-cli/blob/a0345b837371288062b4c64d874df03bbdd8cf6d/src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java#L43-L45

### PR DESCRIPTION
**Pull request by by-su**
## Changes made
- Added `noProgress` parameter: Allows disabling the progress display during the download process.
- **Backward Compatibility**: Existing method calls remain functional as overloaded methods with default `noProgress = false` are provided.

## How to test 
To run the CLI application with the following arguments:
1. To test `FileDownload`
```
file download locale/en.json -d ./example --no-progress
```
2. To test `FileDownloadTranslation`
```
file download locale/en.json -l en -d ./example --no-progress
```

This closes #878

### CODE REVIEW

File: src/main/java/com/crowdin/cli/commands/Actions.java [hunk 1]
```diff
@@ -142,8 +142,12 @@ NewAction<PropertiesWithFiles, ProjectClient> preTranslate(
 
     NewAction<ProjectProperties, ProjectClient> fileDownload(String file, String branch, String destParam);
 
+    NewAction<ProjectProperties, ProjectClient> fileDownload(String file, String branch, boolean noProgress, String destParam);
```
Comment (yevheniyJ) [inline src/main/java/com/crowdin/cli/commands/Actions.java:143]: I would suggest to delete prev version of this method and just keep this one with extra argument, same for `fileDownloadTranslation`.

Comment (by-su) [reply src/main/java/com/crowdin/cli/commands/Actions.java:143]: @yevheniyJ I followed your suggestion and updated them accordingly.

**Review by yevheniyJ — APPROVED** [review]

File: src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java [hunk 2]
```diff
@@ -174,12 +174,12 @@ void testFileUploadTranslation() {
...
     @Test
     void testFileDownload() {
-        assertNotNull(actions.fileDownload(null, null, null));
+        assertNotNull(actions.fileDownload(null, null, false, null));
     }
 
     @Test
     void testFileDownloadTranslation() {
-        assertNotNull(actions.fileDownloadTranslation(null, null,null, null));
+        assertNotNull(actions.fileDownloadTranslation(null, null,null, false,null));
```
Comment (andrii-bodnar) [inline src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java]:
```suggestion
        assertNotNull(actions.fileDownloadTranslation(null, null,null, false, null));
```

File: src/test/java/com/crowdin/cli/commands/actions/FileDownloadActionTest.java [hunk 3]
```diff
@@ -54,7 +54,7 @@ public void testDownload() {
         when(client.downloadFile(eq(101L)))
             .thenReturn(urlMock);
 
-        NewAction<ProjectProperties, ProjectClient> action = new FileDownloadAction("first.po", null, "dest");
+        NewAction<ProjectProperties, ProjectClient> action = new FileDownloadAction("first.po", null, false,"dest");
```
Comment (andrii-bodnar) [inline src/test/java/com/crowdin/cli/commands/actions/FileDownloadActionTest.java]:
```suggestion
        NewAction<ProjectProperties, ProjectClient> action = new FileDownloadAction("first.po", null, false, "dest");
```

File: src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java [hunk 4]
```diff
@@ -29,13 +29,22 @@ class FileDownloadAction implements NewAction<ProjectProperties, ProjectClient>
...
+    private final boolean noProgress;
     private final String dest;
 
+    public FileDownloadAction(String file, String branch, String dest) {
+        this.file = file;
+        this.branch = branch;
+        this.noProgress = false;
+        this.dest = dest;
+    }
+
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java:41]:
```suggestion
```

File: src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java [hunk 5]
```diff
@@ -29,13 +29,22 @@ class FileDownloadAction implements NewAction<ProjectProperties, ProjectClient>
...
+
     @Override
     public void act(Outputter out, ProjectProperties properties, ProjectClient client) {
         CrowdinProjectFull project = ConsoleSpinner
             .execute(out, "message.spinner.fetching_project_info", "error.collect_project_info",
-                false, false, () -> client.downloadFullProject(branch));
+                    noProgress, false, () -> client.downloadFullProject(branch));
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java]:
```suggestion
                noProgress, false, () -> client.downloadFullProject(branch));
```

File: src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java [hunk 6]
```diff
@@ -56,7 +65,7 @@ public void act(Outputter out, ProjectProperties properties, ProjectClient clien
             out,
             "message.spinner.downloading_file",
             "error.downloading_file",
-            false,
+                noProgress,
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java]:
```suggestion
            noProgress,
```

File: src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java [hunk 7]
```diff
@@ -36,13 +36,14 @@ public class FileDownloadTranslationAction implements NewAction<ProjectPropertie
...
     private final String branch;
+    private final boolean noProgress;
     private final String dest;
 
     @Override
     public void act(Outputter out, ProjectProperties properties, ProjectClient client) {
         CrowdinProjectFull project = ConsoleSpinner
             .execute(out, "message.spinner.fetching_project_info", "error.collect_project_info",
-                false, false, client::downloadFullProject);
+                    noProgress, false, client::downloadFullProject);
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java]:
```suggestion
                noProgress, false, client::downloadFullProject);
```

File: src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java [hunk 8]
```diff
@@ -82,7 +83,7 @@ public void act(Outputter out, ProjectProperties properties, ProjectClient clien
                 out,
                 "message.spinner.building_translation",
                 "error.building_translation",
-                false,
+                    noProgress,
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java]:
```suggestion
                noProgress,
```

File: src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java [hunk 9]
```diff
@@ -99,7 +100,7 @@ private void saveToFile(String destPath, URL url, Outputter out) {
             out,
             "message.spinner.downloading_translation",
             "error.write_file",
-            false,
+                noProgress,
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java]:
```suggestion
            noProgress,
```

**Review by andrii-bodnar — CHANGES_REQUESTED** [review]
