### PR TITLE
fix: download sources with double asterisk

### LINKED ISSUE #519: `download sources` doesn't handle configuration files with `**` wildcards in `source` when  `dest` is configured
**Describe the bug**

When using a `**` wildcardis used in a `source` property of a `file` object in the configuration in addition to a `dest` property, the `download source` command does not find source files and display the following warning message:

```
⚠️  No sources found for '/folder_on_crowdin/%original_path%/%file_name%.properties' pattern. Check the source paths in your configuration file
```

**To Reproduce**
1. Configuration file: 

```json

"base_path": "."
"preserve_hierarchy": true

"files": [
    {
    "source": "folder1/folder2/**/messages.properties",
    "dest" : "/folder_on_crowdin/%original_path%/%file_name%.properties",
    "translation": "folder1/folder2/**/%file_name%_%two_letters_code%.properties"
   }
]
```

3. Execute CLI command: 
```
crowdin download sources -b <branch> -i <projectId> -T <api_token>
```
5. See an error

```
⚠️  No sources found for '/folder_on_crowdin/%original_path%/%file_name%.properties' pattern. Check the source paths in your configuration file
```

**Expected behavior**
Source files should be found and downloaded.

**Environment:**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

I found a painful workaround by removing the `**` wildcard and explicit all my path in the configuration file.

```json

"base_path": "."
"preserve_hierarchy": true

"files": [
    {
    "source": "folder1/folder2/folder3/folder4/messages.properties",
    "dest" : "/folder_on_crowdin/folder1/folder2/folder3/folder4/%file_name%.properties",
    "translation": "folder1/folder2/folder3/folder4/%file_name%_%two_letters_code%.properties"
   }
]
```
In my use case, it requires having 90+ `file` objects in my configuration.

### PR DESCRIPTION
**Pull request by yzerk**

### CODE REVIEW

File: src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java [hunk 1]
```diff
@@ -187,8 +187,10 @@ public String replaceFileDependentPlaceholders(String toFormat, File file) {
         toFormat = toFormat.contains(PLACEHOLDER_ORIGINAL_PATH) ? toFormat.replace(PLACEHOLDER_ORIGINAL_PATH, fileParent) : toFormat;
 
         if (toFormat.contains("**")) {
+            String prefix = StringUtils.substringBefore(toFormat, "**");
+            prefix = prefix.length()>1 && file.getPath().contains(prefix) ? StringUtils.substringBefore(fileParent,prefix)  : "";
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java]:
```suggestion
            prefix = prefix.length() > 1 && file.getPath().contains(prefix) ? StringUtils.substringBefore(fileParent,prefix) : "";
```

File: src/main/java/com/crowdin/cli/commands/functionality/TranslationsUtils.java [hunk 2]
```diff
@@ -28,7 +28,8 @@ public static String replaceDoubleAsterisk(String sourcePattern, String translat
         String[] sourceNodes = sourcePattern.split("\\*\\*");
         for (int i = 0; i < sourceNodes.length; i++) {
             if (sourceFile.contains(sourceNodes[i])) {
-                sourceFile = sourceFile.replaceFirst(Utils.regexPath(sourceNodes[i]), "");
+                sourceFile = StringUtils.substring(sourceFile, sourceFile.indexOf(Utils.regexPath(sourceNodes[i])), sourceFile.length()-1)
```
Comment (andrii-bodnar) [inline src/main/java/com/crowdin/cli/commands/functionality/TranslationsUtils.java]:
```suggestion
                sourceFile = StringUtils.substring(sourceFile, sourceFile.indexOf(Utils.regexPath(sourceNodes[i])), sourceFile.length() - 1)
```

**Review by andrii-bodnar — APPROVED** [review]
